Feature/hay 12
hayashisij/V-Coin-Trader pull request #11
Opened 2021-08-15 15:04 UTC by hayashisij

APIのwrapperと復号化したAPI keyを取得する処理を追加。

動作検証でAPI keyを使用した情報を取得しようとしたが401になってしまう。
原因までは分かっていないので、調査が必要。

bitflyer.pyからcrypt.pyをimportしようとすると同名のモジュールをimportしてしまう。
動作検証時は一時的にcrypt.pyを別ディレクトリに移動して行った。
windows由来の問題か、単純に書き方の問題なのかは調査中。

2021-08-20 09:57 UTC, waku1123 requested changes
コメントしましたー

2021-08-20 09:58 UTC, waku1123 commented on lib/bitflyer.py
> +        api_key: str = ""
インスタンス変数じゃなくて良いです？

2021-08-20 09:58 UTC, waku1123 commented on lib/bitflyer.py
> +        api_secret_key: str = ""
インスタンス変数じゃなくて良いです？

2021-08-20 09:58 UTC, waku1123 commented on lib/bitflyer.py
> +        api_key, api_secret_key = crypt.load()
インスタンス変数じゃなくて良いです？

2021-08-29 04:10 UTC, hayashisij commented on lib/bitflyer.py
> +        api_secret_key: str = ""
api_keyとapi_secret_keyにself.を付けてインスタンス変数にしました

2021-08-29 07:46 UTC, waku1123 approved these changes
行ったんんapproveします

2021-08-29 07:49 UTC, merged